/* Find It! V2 - sole navigation controller + sole state poller */
(function(){
 const state={screen:"splashScreen",session:null,game:null,localActivity:null,pollTimer:null,polling:false,pollEnabled:false};
 function showMessage(id,message,isError){const el=document.getElementById(id);if(!el)return;el.textContent=message||"";el.classList.toggle("error",!!isError);}
 function navigate(screenId,options){const target=document.getElementById(screenId);if(!target)throw new Error("Unknown screen: "+screenId);document.querySelectorAll(".screen").forEach(el=>{el.classList.remove("active");el.hidden=true;});target.hidden=false;target.classList.add("active");state.screen=screenId;state.localActivity=options&&options.activity?options.activity:null;window.scrollTo(0,0);}
 function syncSessionFromServer(data){if(!data||!data.player||!state.session)return;const p=data.player,next={gameCode:p.gameCode||data.game.gameCode,playerId:p.playerId,playerName:p.name,isHost:p.isHost===true};if(state.session.gameCode!==String(next.gameCode).toUpperCase()||state.session.playerId!==String(next.playerId)||state.session.playerName!==String(next.playerName)||state.session.isHost!==next.isHost)state.session=FindItSession.set(next);}
 function renderLobby(data){syncSessionFromServer(data);document.getElementById("lobbyGameCode").textContent=data.game.gameCode;const list=document.getElementById("lobbyPlayers");list.innerHTML="";data.players.forEach(player=>{const li=document.createElement("li");li.textContent=player.name+(player.isHost?" (Host)":"");list.appendChild(li);});const start=document.getElementById("startGameButton"),serverIsHost=!!(data.player&&data.player.isHost===true);start.hidden=!serverIsHost;start.disabled=!serverIsHost;document.getElementById("lobbyMessage").textContent=serverIsHost?"When everyone has joined, start the game.":"Waiting for the host to start the game…";}
 function routeServerState(data){syncSessionFromServer(data);const previousStatus=state.game&&state.game.status;state.game=data.game;if(data.game.status==="WAITING"){if(state.screen!=="lobbyScreen")navigate("lobbyScreen");renderLobby(data);return;}if(data.game.status==="PLAYING"){if(state.localActivity==="photo")return;const entering=state.screen!=="challengesScreen"||previousStatus!=="PLAYING";if(state.screen!=="challengesScreen")navigate("challengesScreen");document.getElementById("challengePlayerName").textContent=(data.player&&data.player.name)||state.session.playerName;document.getElementById("challengeGameCode").textContent=data.game.gameCode;if(window.FindItChallenges&&(entering||!document.getElementById("challengeCards").children.length))window.FindItChallenges.load();return;}if(data.game.status==="VOTING"){const entering=state.screen!=="votingIntroScreen"||previousStatus!=="VOTING";if(state.screen!=="votingIntroScreen")navigate("votingIntroScreen");if(entering&&window.FindItVoting)window.FindItVoting.load();return;}if(data.game.status==="FINISHED"){const entering=state.screen!=="resultsScreen"||previousStatus!=="FINISHED";stopPolling();if(state.screen!=="resultsScreen")navigate("resultsScreen");if(entering&&window.FindItResults)window.FindItResults.load();}}
 function scheduleNextPoll(delay){if(!state.pollEnabled||!FindItSession.valid(state.session))return;if(state.pollTimer)clearTimeout(state.pollTimer);state.pollTimer=setTimeout(async()=>{state.pollTimer=null;await pollNow();if(state.pollEnabled&&FindItSession.valid(state.session))scheduleNextPoll(window.FINDIT_CONFIG.pollMs);},delay);}
 async function pollNow(){if(state.polling||!FindItSession.valid(state.session))return;state.polling=true;try{const data=await FindItAPI.get("getGameState",{gameCode:state.session.gameCode,playerId:state.session.playerId,_t:Date.now()});routeServerState(data);showMessage("globalMessage","",false);}catch(error){console.warn("[FindIt App] getGameState poll failed; preserving current screen and retrying on next poll.",error);if(error.code==="SESSION_INVALID"||error.code==="GAME_NOT_FOUND"){stopPolling();FindItSession.clear();state.session=null;navigate("splashScreen");}}finally{state.polling=false;}}
 function startPolling(){stopPolling();state.pollEnabled=true;scheduleNextPoll(0);}
 function ensurePolling(){if(!state.pollEnabled&&FindItSession.valid(state.session)){state.pollEnabled=true;scheduleNextPoll(0);}}
 function stopPolling(){state.pollEnabled=false;if(state.pollTimer)clearTimeout(state.pollTimer);state.pollTimer=null;}
 function restore(){stopPolling();state.polling=false;FindItSession.clear();state.session=null;state.game=null;state.localActivity=null;navigate("splashScreen");}
 window.FindItApp={state,navigate,showMessage,setSession(session){state.session=FindItSession.set(session);state.game=null;state.localActivity=null;startPolling();},clearSession(){stopPolling();state.polling=false;FindItSession.clear();state.session=null;state.game=null;state.localActivity=null;navigate("splashScreen");},pollNow,startPolling,ensurePolling,stopPolling,restore};
 document.addEventListener("DOMContentLoaded",restore);
})();
