/* Find It! V2 - anonymous voting UI */
(function(){let current=null,busy=false;
 async function load(){const s=FindItApp.state.session;if(!s||FindItApp.state.game?.status!=="VOTING"||busy)return;try{const data=await FindItAPI.get("getVotingState",{gameCode:s.gameCode,playerId:s.playerId});render(data);if(s.isHost)loadProgress();}catch(error){FindItApp.showMessage("votingMessage",error.message,true);}}
 function render(data){const area=document.getElementById("votingArea");if(data.complete){current=null;area.innerHTML='<div class="panel completion-panel"><h3>Votes submitted!</h3><p>'+(data.allVotingComplete?'Everyone has finished voting.':'Waiting for the other players to finish voting...')+'</p></div>';return;}current=data;document.getElementById("votingChallengeNumber").textContent="Challenge "+data.challenge.challengeNumber;document.getElementById("votingChallengeName").textContent=data.challenge.name;document.getElementById("selfVoteNotice").textContent=data.selfVoteUsed?"Your one self-vote has already been used.":"You may vote for your own photo once during the whole game.";area.innerHTML='<div class="vote-grid">'+data.options.map(o=>'<button type="button" class="vote-card" data-entry="'+o.optionId+'"><img src="'+o.photoUrl+'" alt="Anonymous challenge photo"><strong>'+o.label+'</strong></button>').join('')+'</div>';area.querySelectorAll(".vote-card").forEach(b=>b.addEventListener("click",()=>vote(b.dataset.entry)));}
 async function vote(entryId){if(!current||busy)return;if(!window.confirm("Vote for this photo?"))return;busy=true;try{const s=FindItApp.state.session;await FindItAPI.post("castVote",{gameCode:s.gameCode,playerId:s.playerId,challengeId:current.challenge.challengeId,entryId:entryId});current=null;await load();}catch(error){FindItApp.showMessage("votingMessage",error.message,true);}finally{busy=false;}}
 async function loadProgress(){const s=FindItApp.state.session;try{const data=await FindItAPI.get("getVotingProgress",{gameCode:s.gameCode,playerId:s.playerId}),box=document.getElementById("votingProgress");box.hidden=false;box.innerHTML='<h3>Voting progress</h3>'+data.players.map(p=>'<div class="player-progress"><span>'+escapeHtml(p.name)+(p.isHost?' (Host)':'')+'</span><strong>'+(p.complete?'Done ✓':'Voting…')+'</strong></div>').join('')+(data.allVotingComplete?'<p class="ready-note">Everyone has voted.</p>':'');}catch(_) {}}
 function escapeHtml(v){return String(v||"").replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
 window.FindItVoting={load};
})();
